name: Build and Publish JupyterBook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Test Push
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_WEBSITE_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b test-branch
        touch test-file.txt
        git add test-file.txt
        git commit -m "Test commit"
        git push origin test-branch

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book ghp-import

    - name: Build JupyterBook
      run: jupyter-book build .

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_WEBSITE_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        ghp-import -n -p -f _build/html -b gh-pages